project:
  type: website

website:
  title: "R/Tidyverse/Quarto get started"
  navbar:
    left:
      - href: index.qmd
        text: ⠀
        icon: house
      - text: Import/Wrangle
        menu: 
          - text: Reproducible projects
            icon: folder
            href: proj.qmd
          - text: Import data
            icon: upload
            href: import.qmd
          - text: Wrangle {dplyr}
            icon: funnel
            href: wrangle.qmd
          - text: Pivot data (tall or wide)
            icon: arrow-repeat
            href: longer_wider.qmd
          - text: Join data frames
            icon: intersect
            href: join.qmd
      - text: Visualization
        menu:
          - text: Get started with ggplot2
            icon: bar-chart
            href: viz.qmd
          - text: Interactivity
            icon: hand-index
            href: interactive.qmd            
      - text: Models/Regression
        menu:
          - text: regression
            icon: graph-up
            href: regression.qmd
          - text: tidymodels
            icon: gpu-card
            href: tidymodels.qmd
      - text: Functions & iteration
        menu:
          - text: Custom functions
            icon: braces
            href: functions.qmd
          - text: Iteration with {purrr}
            icon: arrow-clockwise
            href: purrr.qmd            
      - text: Examples
        menu:
          - text: Quick start
            icon: skip-start
            href: quick_start.qmd
          - text: Exploratory Data Analysis (EDA)
            icon: eye-fill
            href: tidy_tuesday_itra.qmd
      - about.qmd

format:
  html:
    df-print: paged
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

