project:
  type: website

website:
  title: "R/Tidyverse/Quarto - get started"
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
  page-footer: 
    background: light
    left: "<a href='https://JohnLittle.info'>John Little</a>"
    center: "<a href='https://rfun.library.duke.edu'>Rfun</a> ● <a href='https://library.duke.edu/data'>Center for Data & Visualization Sciences</a>"
    right: "<a href='https://library.duke.edu/'>Duke University Libraries</a>"
  navbar: 
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/libjohn/casestudy_reproducible_workflow_census
        aria-label: GitHub
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Home"
        contents:
          - href: index.qmd
          - text: Data and code
            href: data.qmd
          - text: Download/install/packages
            href: packages.qmd
      - section: "Get Started"
        contents:
          - text: Projects (Reproducibility)
            href: proj.qmd
          - text: Import data
            href: import.qmd
          - text: Wrangle {dplyr}
            href: wrangle.qmd
          - text: Pivot data (tall or wide)
            href: longer_wider.qmd
          - text: Join data frames
            href: join.qmd
      - section: Visualization
        contents:
          - text: Get started with ggplot2
            href: viz.qmd
          - text: Interactivity
            href: interactive.qmd            
      - section: Models/Regression
        contents:
          - text: Regression
            href: regression.qmd
          - text: Tidymodels
            href: tidymodels.qmd
      - section: Functions & iteration
        contents:
          - text: Custom functions
            href: functions.qmd
          - text: Iteration with {purrr}
            href: purrr.qmd            
      - section: Examples
        contents:
          - text: Exploratory Data Analysis (EDA)
            href: tidy_tuesday_itra.qmd

format:
  html:
    df-print: paged
    theme: sandstone
    css: styles.css
    toc: true

editor: visual



